In [1]:
import pandas as pd

In [24]:
preprocessed = pd.read_csv('../data/preprocessed/samsung_preprocess.csv',
                           encoding='cp949',
                           index_col=0)
preprocessed = preprocessed.reset_index()

marcap_n = pd.read_csv('../data/origin/krx/삼성전자_marcap.csv',
                      encoding='cp949')

marcap_f = pd.read_csv('../data/origin/krx/삼성전자_marcap.csv',
                        encoding='cp949')

In [8]:
preprocessed.columns

Index(['날짜', '1일 뒤 종가', '2일 뒤 종가', '3일 뒤 종가', '4일 뒤 종가', '5일 뒤 종가', '거래량',
       '개인', '기관', '외인수량', '외국계', '프로그램', '보고일자', '공시-변동 차이', '변동전', '증감',
       '보고구분_변동', '보고구분_신규', '보고자 구분_개인(국내)', '보고자 구분_개인(외국)',
       '보고자 구분_연기금등 전문투자자', '임원_-', '임원_등기임원', '임원_비등기임원', '직위명_ 상무', '직위명_-',
       '직위명_대표이사 부회장', '직위명_대표이사 사장', '직위명_대표이사부회장', '직위명_대표이사회장', '직위명_부사장',
       '직위명_부회장', '직위명_사외이사', '직위명_사장', '직위명_상무', '직위명_상임고문', '직위명_전무',
       '직위명_회장', '주요주주_-', '주요주주_10%이상주주', '주요주주_사실상지배주주', '변동사유_계열사편입(+)',
       '변동사유_기타(+)', '변동사유_기타(-)', '변동사유_상속(+)', '변동사유_시간외매매(-)',
       '변동사유_신규등록(+)', '변동사유_신규보고(+)', '변동사유_신규선임(+)', '변동사유_신규주요주주(+)',
       '변동사유_임원퇴임(-)', '변동사유_장내매도(-)', '변동사유_장내매수(+)', '변동사유_장외매도(-)',
       '변동사유_주식매수선택권(+)', '변동사유_주식분할', '변동사유_증여(-)', '변동사유_피상속(-)',
       '특정증권등의 종류_기타', '특정증권등의 종류_보통주', '특정증권등의 종류_우선주'],
      dtype='object')

In [32]:
df_n = pd.merge(preprocessed.loc[preprocessed['특정증권등의 종류_보통주'] == 1,['index', '날짜']],
         marcap_n[['Date', 'Adj Close', 'Stocks']],
         how='left',
         left_on='날짜',
         right_on='Date'
)
df_n = df_n.drop(columns = ['Date'])

df_f = pd.merge(preprocessed.loc[preprocessed['특정증권등의 종류_우선주'] == 1,['index', '날짜']],
         marcap_n[['Date', 'Adj Close', 'Stocks']],
         how='left',
         left_on='날짜',
         right_on='Date'
)
df_f = df_f.drop(columns=['Date'])

df = pd.concat([df_f, df_n])
df = df.drop(columns='날짜')

In [38]:
result = pd.merge(preprocessed, df, on='index')
result = result.drop(columns=['index', 'Adj Close'])
result = result.rename(columns={'Stocks':'상장주식수'})
result

,날짜,1일 뒤 종가,2일 뒤 종가,3일 뒤 종가,4일 뒤 종가,5일 뒤 종가,거래량,개인,기관,외인수량,...,변동사유_장내매수(+),변동사유_장외매도(-),변동사유_주식매수선택권(+),변동사유_주식분할,변동사유_증여(-),변동사유_피상속(-),특정증권등의 종류_기타,특정증권등의 종류_보통주,특정증권등의 종류_우선주,상장주식수
0,2022-10-24,1.0,1.0,1.0,0.0,1.0,16944503.0,-295570.0,90192.0,4052733.0,...,1,0,0,0,0,0,0,0,1,5.969783e+09
1,2022-10-24,1.0,1.0,1.0,0.0,1.0,16944503.0,-295570.0,90192.0,4052733.0,...,0,0,0,0,0,0,0,0,1,5.969783e+09
2,2022-10-18,0.0,0.0,0.0,1.0,1.0,14820702.0,90894.0,-21724.0,2647435.0,...,1,0,0,0,0,0,0,1,0,5.969783e+09
3,2022-10-18,0.0,0.0,0.0,1.0,1.0,14820702.0,90894.0,-21724.0,2647435.0,...,1,0,0,0,0,0,0,0,1,5.969783e+09
4,2022-10-17,0.0,0.0,0.0,0.0,1.0,13641878.0,-72081.0,-70512.0,1274596.0,...,1,0,0,0,0,0,0,1,0,5.969783e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2165,2015-01-15,0.0,1.0,1.0,1.0,1.0,282078.0,-15681.0,10355.0,-71115.0,...,0,0,0,0,0,0,0,1,0,1.472993e+08
2166,2015-01-14,0.0,0.0,0.0,1.0,1.0,286645.0,-66088.0,10288.0,-4171.0,...,0,0,0,0,0,0,0,1,0,1.472993e+08
2167,2015-01-14,0.0,0.0,0.0,1.0,1.0,286645.0,-66088.0,10288.0,-4171.0,...,0,0,0,0,0,0,0,1,0,1.472993e+08
2168,2015-01-13,1.0,0.0,0.0,1.0,1.0,245868.0,-26741.0,-28117.0,-7144.0,...,0,0,0,0,0,0,0,1,0,1.472993e+08
2169,2015-01-13,1.0,0.0,0.0,1.0,1.0,245868.0,-26741.0,-28117.0,-7144.0,...,0,0,0,0,0,0,0,1,0,1.472993e+08

In [41]:
result.to_csv('../data/preprocessed/20150101-20221024_삼성전자_d002_with_stocks.csv',
              encoding='cp949',
              index=False)

In [42]:
result.columns

Index(['날짜', '1일 뒤 종가', '2일 뒤 종가', '3일 뒤 종가', '4일 뒤 종가', '5일 뒤 종가', '거래량',
       '개인', '기관', '외인수량', '외국계', '프로그램', '보고일자', '공시-변동 차이', '변동전', '증감',
       '보고구분_변동', '보고구분_신규', '보고자 구분_개인(국내)', '보고자 구분_개인(외국)',
       '보고자 구분_연기금등 전문투자자', '임원_-', '임원_등기임원', '임원_비등기임원', '직위명_ 상무', '직위명_-',
       '직위명_대표이사 부회장', '직위명_대표이사 사장', '직위명_대표이사부회장', '직위명_대표이사회장', '직위명_부사장',
       '직위명_부회장', '직위명_사외이사', '직위명_사장', '직위명_상무', '직위명_상임고문', '직위명_전무',
       '직위명_회장', '주요주주_-', '주요주주_10%이상주주', '주요주주_사실상지배주주', '변동사유_계열사편입(+)',
       '변동사유_기타(+)', '변동사유_기타(-)', '변동사유_상속(+)', '변동사유_시간외매매(-)',
       '변동사유_신규등록(+)', '변동사유_신규보고(+)', '변동사유_신규선임(+)', '변동사유_신규주요주주(+)',
       '변동사유_임원퇴임(-)', '변동사유_장내매도(-)', '변동사유_장내매수(+)', '변동사유_장외매도(-)',
       '변동사유_주식매수선택권(+)', '변동사유_주식분할', '변동사유_증여(-)', '변동사유_피상속(-)',
       '특정증권등의 종류_기타', '특정증권등의 종류_보통주', '특정증권등의 종류_우선주', '상장주식수'],
      dtype='object')

In [49]:
use_cols = ['거래량', '개인','기관', '외인수량', '외국계', '프로그램', '변동전', '증감']
result_df = result.copy()
for col in use_cols:
    result_df[col] = result_df.apply(lambda x: x[col]/x['상장주식수']*100, axis=1)
    
result_df[use_cols]

,거래량,개인,기관,외인수량,외국계,프로그램,변동전,증감
0,0.283838,-0.004951,0.001511,0.067887,0.004114,0.001279,1.675103e-06,3.350206e-06
1,0.283838,-0.004951,0.001511,0.067887,0.004114,0.001279,0.000000e+00,1.675103e-06
2,0.248262,0.001523,-0.000364,0.044347,-0.000412,-0.001975,0.000000e+00,6.197881e-06
3,0.248262,0.001523,-0.000364,0.044347,-0.000412,-0.001975,2.948181e-06,3.534467e-06
4,0.228515,-0.001207,-0.001181,0.021351,0.001464,0.001931,1.005062e-05,3.484214e-06
...,...,...,...,...,...,...,...,...
2165,0.191500,-0.010646,0.007030,-0.048279,-0.068457,0.014426,8.825566e-06,0.000000e+00
2166,0.194600,-0.044866,0.006984,-0.002832,0.040021,-0.007689,0.000000e+00,6.788897e-07
2167,0.194600,-0.044866,0.006984,-0.002832,0.040021,-0.007689,6.788897e-07,-6.788897e-07
2168,0.166917,-0.018154,-0.019088,-0.004850,0.021836,0.016222,1.086223e-04,-1.086223e-04
2169,0.166917,-0.018154,-0.019088,-0.004850,0.021836,0.016222,1.765113e-04,-6.788897e-05

In [50]:
result_df.to_csv('../data/preprocessed/20150101-20221024_삼성전자_d002_with_stocks_ratio.csv',
              encoding='cp949',
              index=False)